### ISSUE TITLE
Handle network timeouts

### ISSUE THREAD

**Issue by s2t2** [prof-rossetti/bikeshare-data#1]
bikeshare file is incomplete due to network timeouts (max attempts) resulting from requesting stations from the "bicipalma" network.

``` py
{'id': 3, 'name': 'bicipalma', 'radius': 20000}
Traceback (most recent call last):
  File "extract_bikeshare_data.py", line 74, in <module>
    response.update()
  File "/usr/local/lib/python2.7/site-packages/pybikes/bicipalma.py", line 37, in update
    scraper.request(COOKIE_URL)
  File "/usr/local/lib/python2.7/site-packages/pybikes/utils.py", line 80, in request
    verify = False
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 357, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 460, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 354, in send
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='83.36.51.60', port=8080): Max retries exceeded with url: /eTraffic3/Control?act=mp (Caused by <class 'socket.error'>: [Errno 60] Operation timed out)
```

**Comment by s2t2** [comment]
``` py
{'id': 120, 'name': 'bizi', 'radius': 20000}
Traceback (most recent call last):
  File "extract_bikeshare_data.py", line 85, in <module>
    response.update() # makes an api call for the stations...
  File "/usr/local/lib/python2.7/site-packages/pybikes/smartbike.py", line 49, in update
    raw_req = scraper.request(self.feed_url)
  File "/usr/local/lib/python2.7/site-packages/pybikes/utils.py", line 80, in request
    verify = False
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 357, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 460, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 354, in send
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.bizizaragoza.com', port=443): Max retries exceeded with url: /es/formmap/getJsonObject (Caused by <class 'socket.gaierror'>: [Errno 8] nodename nor servname provided, or not known)
```

**Comment by s2t2** [comment]
just skipping over these errors with `except: continue` statements for now...
